version: '3.9'
services:
  postfix:
    image: 'juanluisbaptiste/postfix:latest'
    build:
      context: ./postfix
      dockerfile: Dockerfile.dev
    expose:
    - "25"
    env_file:
      - "./postfix/.env"
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
    
  postgres:
      image: 'postgres:latest'
      environment:
        - POSTGRES_USER=root
        - POSTGRES_DB=mail_server
        - POSTGRES_ROOT_PASSWORD=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_HOST_AUTH_METHOD=trust
        - POSTGRES_DB_HOST=127.0.0.1
      restart: always
      ports:
          - "5432:5432"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
      build:
          context: ./server
          dockerfile: Dockerfile.dev
      volumes:
          - /app/node_modules
          - ./server:/app
      restart: always
      environment:
        - pgUser=root
        - pgHost=root
        - pgDatabase=mail_server
        - pgPassword=root
        - pgPort=5432
      ports:
          - "5000:5000"

  client:
      build:
          context: ./client
          dockerfile: Dockerfile.dev
      volumes:
          - /app/node_modules
          - ./client:/app
      ports:
          - "3000:3000"